### ISSUE TITLE
[vite] Internal server error: Failed to resolve entry for package "utm-synapse". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by hassankotti** [sneko/utm-synapse#2]
## Current Behavior

after install the package there is runtime error

## Expected Behavior

vite support

## Steps to Reproduce the Problem

1.  installing the pkg using `pnpm` in vite react app
2.  run dev

## Environment

- Version: ^1.2.1
- Platform: Mac
- Node.js Version: v18.20.3

**Comment by sneko** [comment]
@hassankotti could you please share here the error logs you have?

**Comment by sneko** [comment]
Hi @hassankotti , thank you for reporting the issue.

I just published a fix into `v1.2.2`.
